### PR TITLE
chore: upgrade peer dependecy tslint-prettier-config

### PR DESCRIPTION
**Pull request by Poltergeist**
tslint-prettier-config 1.11.0 was released today we should put this as our new peer dependency.

### CODE REVIEW

**Review by DanielMSchmidt — APPROVED** [review]

**Comment by nLight** [comment]
Shall we go straight to 1.12.0?

**Comment by DanielMSchmidt** [comment]
@nLight Sounds good!

**Comment by Poltergeist** [comment]
Did that.

**Review by weblancaster — APPROVED** [review]
LGTM

**Pull request merged**
